In [ ]:
import pandas as pd
import numpy as np 
# these are the imports

In [ ]:
df = pd.read_csv('/Users/apple/Downloads/chicago_taxi_train.csv')
df = df.loc[:, ['TRIP_MILES', 'TRIP_SECONDS', 'FARE', 'COMPANY', 'PAYMENT_TYPE', 'TIP_RATE']]
df.head(200)

,TRIP_MILES,TRIP_SECONDS,FARE,COMPANY,PAYMENT_TYPE,TIP_RATE
0,2.57,2341,31.99,Flash Cab,Mobile,6.3
1,1.18,1074,9.75,Flash Cab,Credit Card,27.9
2,1.29,1173,10.25,Sun Taxi,Cash,0.0
3,3.70,3360,23.75,Choice Taxi Association,Cash,0.0
4,1.15,1044,10.00,Flash Cab,Cash,0.0
...,...,...,...,...,...,...
195,1.13,821,9.00,Blue Ribbon Taxi Association,Mobile,22.9
196,0.57,414,6.00,Flash Cab,Cash,0.0
197,1.22,886,9.00,City Service,Cash,0.0
198,1.68,1219,9.00,Sun Taxi,Mobile,23.0
199,0.71,515,6.50,Sun Taxi,Credit Card,18.2

In [ ]:
data = {
'patient_id': [101, 102, 103],
'age': [45, 60, 38],
'diagnosis': ['benign', 'malignant', 'benign'],
'nodule_size':[1.2, 3.5, 0.8]
} # lets assume that this is the data

df = pd.DataFrame(data)
df.head()
# this is how we handle data in the form of table

   patient_id  age  diagnosis  nodule_size
0         101   45     benign          1.2
1         102   60  malignant          3.5
2         103   38     benign          0.8