In [15]:
import pandas as pd

In [14]:
data = {
'patient_id': [101, 102, 103],
'age': [45, 60, 38],
'diagnosis': ['benign', 'malignant', 'benign'],
'nodule_size':[1.2, 3.5, 0.8]
} # lets assume that this is the data

df = pd.DataFrame(data)
df.head()
# this is how we handle data in the form of table

   patient_id  age  diagnosis  nodule_size
0         101   45     benign          1.2
1         102   60  malignant          3.5
2         103   38     benign          0.8

In [ ]:
df = pd.read_csv('/Users/apple/Downloads/chicago_taxi_train.csv', usecols=['TRIP_MILES', 'TRIP_SECONDS', 'FARE', 'COMPANY', 'PAYMENT_TYPE', 'TIP_RATE'])
df.head(200)
df.shape #prints the size of the table 
df.columns # columns name
df.describe() # gives the statistical summary of the data
# very impportant for numerical data

df['TRIP_MILES'].mean() # mean of the column
# one of the collumns are accesed this way - and per statistics too

#searching for data in the data frame
df.loc[0] # this is how we access the row of the data frame - by index
df.loc[5] # fifth row of the data frame
df.loc[0, 'TRIP_MILES'] # this is when we need to access a specific column in any row

np.float64(2.57)

In [ ]:
# here are the boolean conditions

df[df['TRIP_MILES'] > 50] # this is how we can filter the data frame based on a condition
df[df['TRIP_SECONDS'].between(1000, 3000)] # this is how we can filter the data frame based on a condition
df[df['COMPANY'] == 'Flash Cab'] # this is how we can filter the data frame based on a condition

#for multiple conditions we can use & and | operators
df[(df['TRIP_MILES'] > 50) & (df['COMPANY'] == 'Flash Cab')] # this is how we can filter the data frame based on multiple conditions

#if we use .query() method then we can use the column names directly without using the df['column_name'] syntax
df.query('TRIP_MILES > 50 and COMPANY == "Flash Cab"')
#this is simpler as readable

df[df['TRIP_SECONDS'].between(1000, 1010)]

,TRIP_SECONDS,TRIP_MILES,FARE,TIP_RATE,PAYMENT_TYPE,COMPANY
85,1005,1.25,20.00,20.5,Credit Card,Flash Cab
362,1006,1.54,9.75,20.5,Credit Card,Sun Taxi
640,1001,1.70,10.00,0.0,Cash,Chicago Independents
748,1009,1.78,10.00,18.2,Credit Card,City Service
806,1001,1.79,9.00,23.0,Mobile,Taxicab Insurance Agency Llc
...,...,...,...,...,...,...
30848,1001,12.74,32.25,0.0,Prcard,Flash Cab
31199,1001,13.55,34.75,25.2,Credit Card,Sun Taxi
31258,1010,13.84,34.75,0.0,Prcard,Flash Cab
31366,1002,14.12,35.25,20.3,Credit Card,City Service
31382,1003,14.21,35.75,20.3,Credit Card,Star North Taxi Management Llc

In [ ]:
# this is adding and modifying collumns in the data frame
df['is_long_trip'] = df['TRIP_MILES'] > 50 # this is a boolean condition
df['MY_PROFIT'] = df['FARE'] / df['TRIP_MILES']

df[df['is_long_trip'] == True]

# np.where is used for conditions and nested condition

,TRIP_SECONDS,TRIP_MILES,FARE,TIP_RATE,PAYMENT_TYPE,COMPANY,is_long_trip,MY_PROFIT
25763,5885,50.11,120.50,15.1,Credit Card,Globe Taxi,True,2.404710
29195,5520,58.80,139.75,0.0,Cash,Globe Taxi,True,2.376701
30090,4711,54.57,129.75,0.0,Cash,Flash Cab,True,2.377680
30228,5282,62.08,146.75,0.0,Cash,Flash Cab,True,2.363885
30273,5100,60.20,141.50,0.0,Cash,U Taxicab,True,2.350498
30719,5017,62.72,146.00,8.8,Credit Card,Medallion Leasin,True,2.327806
31069,4581,60.60,141.75,0.0,Cash,City Service,True,2.339109
31469,4362,63.41,147.00,0.0,Cash,City Service,True,2.318246
31582,4467,68.12,159.25,0.0,Cash,Flash Cab,True,2.337786
31687,2951,51.90,120.25,20.1,Credit Card,Star North Taxi Management Llc,True,2.316956